service:
- docker

language: java
jdk: oraclejdk8

addons:
  apt:
    update: true
    packages:
    - docker-ce
    - python-pip
    - curl
    - jq
    - libxml2-utils

install: true
before_install:
- sudo pip install docker-compose httpie
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080 9990 9999 5005

env:
  global:
  - TERM=dumb
#  - secure: egfhcFUnF9LBbpdWBWYRqa6qiIzeam1L3C28P0VOxKF2KfMqTkET/B6iwV/Pn6tRLeH964CT2y4Z6JVLtmA8iohXhVUSMCgHOxwmo0gIWv4s4/3/V75NKxHkAmobpVJcHLiLIo6wJbKjQMlvSGB1x4OUU+fzjiiwkZLqidqwZudOFTIcVRA8p1TjfEhnnAaUP3Fa6gU1Trd8lwGh6vmUIgCPPwnxGL2wW29SXMQHLE1FV46VmMeyOpRSqWpnAC/fKDjb+T5mwCGTlV20eLzqcEdhnL2w1oCNh9t6JDhY3BakH3Ck8HNlzqrzfwTwldTMAmcWFvjsDuQcPTy4jaZTnO5fL5RSPRxvUQSlgiLYSpzPBtBZlDDKCyesRDjWs8x8176mqr49dJQ94E9jT7dWFLgXT2rFRgSabwefkArGFd/7uhfu/t0oDH//jVyuCfvbIzDYY5U+HJtFAowTYa4LdPsX5fumK0ngs6ch+MUVPIJQ58y9671mAMefzoELoIvE2YT6nk+RZOxjwkRIBWU2hAjg+V9JQxx2wJlPHBXp/lwxeRvmeUKqvbCq4zDHbDasKAWuVwz0lEeVZHFh7REdGHqbKm/hnXVZx6W/5KPTyjR7CtoV4vjjhZxYlWZ1qRUS7fPqltl5v8PZFu8lRBCP9Uf/CSlr500gktciQOH17UA=
#  - secure: m/hIvFinPie3UYjaGFi149qDsSxQMq489kLgOv0gceLzVosV9MeFWZ45DoZrSMS8ybowH3v4Crq66ChROQX9DGr/rBIORg7ia3RkBTXl+xMuWIF/l1cOzQF2cqkPemUgqTCZF+aV5OAlhIK9XGy5VhIz17B3PGQQVoqabCvL0iZDmBcwj0bCtkp0rJM+pT9+6GIwGNaUxGi2E+6Y19k9aK9KYuLyXSgi/X1o+qqotI08nm6yY/oBsSw4h2kWDeOOw0o7PmYdx6YAizcMZnCnhq7M7aTDYa5RbGNm8BoYx7TNKorSnKxUVlf68ETmu+7R6Jv5dGdOVCpsWsx0z9Ii/98fPtzPjvLyvFznnDjCvJshc1BikPWs4Apfda7EJkZgXdIlNauW1p1JC1LJ5RIJ1lWVl/ebUcTTJdVlXboXbEvaAPIf7dR2nyAxOF5fYhq9hvxBKgNetCZEknltAcrpFwcjKSMN0ZBNyFoVhiH2VFqxANfBsU/RbkZaaluauuwaB7Nn9d96lHuuktw3a9n+WXNuB96/VkBqXnwJvfyrONOIShIsjs4U+uGU9GiYYqy9VxIO9HQMC2LSOzs/SH8CzO51ToLxB5GlEiVKBQwhAIH/sCG+ube0RUAPTYMZFtV/ITAXFXFuiJ4LtFO4jht1IxCzWgL1KrRhblOhhixj5jQ=
  - secure: G0eexJAIM1CTX1wMV5//2Ckfk5yjjwTjJ5eALtCTZ/ueQGKEcBeJ5l/K37lvquaVcRQBkZnK7m55zsj7bfJIRx6HvONvbFe1NMPZO/kl1CT6umOvfNLdzF926yoOBr5RHC+6aZkb4z+JBqJ0dIBpRTZsM8ODN197OeSNgbPUp7rhoY6JiuKwG2AC0Ic2cVI787MOeNqiDhr0aNmY0Kpe7lLICiLmdlvwchaBz4Zsi0v+Wgdu+TuoBQqYyMY79XhsfTN7seScL9iDz7v/qDROJm+ZCLCDLBiEl4YatsFy8Lzeu3E1i8AoWwnirWEw3fC0biIzslRDwAefKiDaJGb9JEOul+FLCaspto2QGfU6AS4lbgp78OcRvUXVQl8CKacAfF2lrfBW7EY6dnyZTcnp83X50pSgIlebiMQH6VSm5CecCbgvoTBwik8r9zhC+AyN58Y/pGTLNjR01KfaSmGcIak+CQ/3RSePA+kRjauFitwBD1XrIWMGNMpbzAAxuXZmNekrvpBcTrIjaFVNx6LCFb+WAjhpTwVaveURsiKk14IbgTtdNbg1Tt9kPiN7Y3VVq+L8BykHYhHJdL4YzFHjyBU6KPpknmnN+Agbblqr7adLEEyIAiq1I2MDjptD/5+lfHRWKRO5tLR3ucMdBanre5wiE4IckCTweSos5xMk6Hc=

script:
#- bash gradlew clean docs -Dorg.ajoberstar.grgit.auth.username=daggerok -Dorg.ajoberstar.grgit.auth.password=$GITHUB_PASSWORD
- export root=$(pwd)
#
- cd ${root}/axon-conference
- bash mvnw >/dev/null
- java -jar target/*.jar &
- wait_for 8080
- http :8080/conference name=ololo
- http :8080/conference
- stop_any 8080
#
- cd ${root}/axon-conference
- ./gradlew >/dev/null
- bash build/libs/*.jar &
- wait_for 8080
- http :8080/conference name=ololo
- http :8080/conference
- stop_any 8080
#
- cd ${root}/java-ee
- bash mvnw
- docker-compose -f docker-compose-maven.yaml build
- docker-compose -f docker-compose-maven.yaml up &
- sleep 40
- http post :8080/app/facebook/create postId=post1
- http put http://localhost:8080/app/facebook/post1/like
- http put http://localhost:8080/app/facebook/post1/dislike
- http put http://localhost:8080/app/facebook/post1/like
- http put http://localhost:8080/app/facebook/post1/like
- http :8080/app/posts/post1
- http :8080/app/posts/post1/events
- docker-compose -f docker-compose-maven.yaml down -v
#
- bash gradlew
- bash gradlew composeUp
- sleep 20
- http post :8080/app/facebook/create postId=post2
- http put http://localhost:8080/app/facebook/post2/dislike
- http :8080/app/posts
- http :8080/app/posts/post2/events
- bash gradlew composeDown

before_deploy: ./gradlew documentation

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: public
  target_branch: gh-pages

before_cache:
- sudo rm -rf $HOME/.gradle/caches/4.8/fileHashes/fileHashes.bin
- sudo rm -rf $HOME/.gradle/caches/4.8/fileHashes/fileHashes.lock
- sudo rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
