service:
- docker
sudo: required
group: travis_lts
env:
  global:
    TERM=dumb
language: java
jdk:
- openjdk8
- oraclejdk8
install: true
before_install:
- sudo apt update -y || true
- sudo apt install -y --no-install-recommends docker-ce python-pip curl jq libxml2-utils
- sudo pip install docker-compose httpie
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017
script:
- bash gradlew
- bash mvnw
