service:
- docker

language: java
jdk: oraclejdk8

addons:
  apt:
    update: true
    packages:
    - docker-ce
    - python-pip
    - curl
    - jq
    - libxml2-utils

install: true
before_install:
- sudo pip install docker-compose httpie
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080 9990 9999 5005

script:
- export root=$(pwd)
#
- cd ${root}/axon-conference
- bash mvnw >/dev/null
- java -jar target/*.jar &
- wait_for 8080
- http :8080/conference name=ololo
- http :8080/conference
- stop_any 8080
#
- cd ${root}/axon-conference
- ./gradlew >/dev/null
- bash build/libs/*.jar &
- wait_for 8080
- http :8080/conference name=ololo
- http :8080/conference
- stop_any 8080
#
- cd ${root}/java-ee
- bash mvnw
- docker-compose -f docker-compose-maven.yaml build
- docker-compose -f docker-compose-maven.yaml up &
- sleep 40
- http post :8080/app/facebook/create postId=post1
- http put http://localhost:8080/app/facebook/post1/like
- http put http://localhost:8080/app/facebook/post1/dislike
- http put http://localhost:8080/app/facebook/post1/like
- http put http://localhost:8080/app/facebook/post1/like
- http :8080/app/posts/post1
- http :8080/app/posts/post1/events
- docker-compose -f docker-compose-maven.yaml down -v
#
- bash gradlew
- bash gradlew composeUp
- sleep 20
- http post :8080/app/facebook/create postId=post2
- http put http://localhost:8080/app/facebook/post2/dislike
- http :8080/app/posts
- http :8080/app/posts/post2/events
- bash gradlew composeDown

env:
  global:
  - TERM=dumb
  - secure: G0eexJAIM1CTX1wMV5//2Ckfk5yjjwTjJ5eALtCTZ/ueQGKEcBeJ5l/K37lvquaVcRQBkZnK7m55zsj7bfJIRx6HvONvbFe1NMPZO/kl1CT6umOvfNLdzF926yoOBr5RHC+6aZkb4z+JBqJ0dIBpRTZsM8ODN197OeSNgbPUp7rhoY6JiuKwG2AC0Ic2cVI787MOeNqiDhr0aNmY0Kpe7lLICiLmdlvwchaBz4Zsi0v+Wgdu+TuoBQqYyMY79XhsfTN7seScL9iDz7v/qDROJm+ZCLCDLBiEl4YatsFy8Lzeu3E1i8AoWwnirWEw3fC0biIzslRDwAefKiDaJGb9JEOul+FLCaspto2QGfU6AS4lbgp78OcRvUXVQl8CKacAfF2lrfBW7EY6dnyZTcnp83X50pSgIlebiMQH6VSm5CecCbgvoTBwik8r9zhC+AyN58Y/pGTLNjR01KfaSmGcIak+CQ/3RSePA+kRjauFitwBD1XrIWMGNMpbzAAxuXZmNekrvpBcTrIjaFVNx6LCFb+WAjhpTwVaveURsiKk14IbgTtdNbg1Tt9kPiN7Y3VVq+L8BykHYhHJdL4YzFHjyBU6KPpknmnN+Agbblqr7adLEEyIAiq1I2MDjptD/5+lfHRWKRO5tLR3ucMdBanre5wiE4IckCTweSos5xMk6Hc=

before_deploy: ./gradlew documentation

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: public
  target_branch: gh-pages

before_cache:
- sudo rm -rf $HOME/.gradle/caches/4.8/fileHashes/fileHashes.bin
- sudo rm -rf $HOME/.gradle/caches/4.8/fileHashes/fileHashes.lock
- sudo rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
