service:
- docker
sudo: required
group: travis_lts
env:
  global:
  - TERM=dumb
  - secure: egfhcFUnF9LBbpdWBWYRqa6qiIzeam1L3C28P0VOxKF2KfMqTkET/B6iwV/Pn6tRLeH964CT2y4Z6JVLtmA8iohXhVUSMCgHOxwmo0gIWv4s4/3/V75NKxHkAmobpVJcHLiLIo6wJbKjQMlvSGB1x4OUU+fzjiiwkZLqidqwZudOFTIcVRA8p1TjfEhnnAaUP3Fa6gU1Trd8lwGh6vmUIgCPPwnxGL2wW29SXMQHLE1FV46VmMeyOpRSqWpnAC/fKDjb+T5mwCGTlV20eLzqcEdhnL2w1oCNh9t6JDhY3BakH3Ck8HNlzqrzfwTwldTMAmcWFvjsDuQcPTy4jaZTnO5fL5RSPRxvUQSlgiLYSpzPBtBZlDDKCyesRDjWs8x8176mqr49dJQ94E9jT7dWFLgXT2rFRgSabwefkArGFd/7uhfu/t0oDH//jVyuCfvbIzDYY5U+HJtFAowTYa4LdPsX5fumK0ngs6ch+MUVPIJQ58y9671mAMefzoELoIvE2YT6nk+RZOxjwkRIBWU2hAjg+V9JQxx2wJlPHBXp/lwxeRvmeUKqvbCq4zDHbDasKAWuVwz0lEeVZHFh7REdGHqbKm/hnXVZx6W/5KPTyjR7CtoV4vjjhZxYlWZ1qRUS7fPqltl5v8PZFu8lRBCP9Uf/CSlr500gktciQOH17UA=
  - secure: m/hIvFinPie3UYjaGFi149qDsSxQMq489kLgOv0gceLzVosV9MeFWZ45DoZrSMS8ybowH3v4Crq66ChROQX9DGr/rBIORg7ia3RkBTXl+xMuWIF/l1cOzQF2cqkPemUgqTCZF+aV5OAlhIK9XGy5VhIz17B3PGQQVoqabCvL0iZDmBcwj0bCtkp0rJM+pT9+6GIwGNaUxGi2E+6Y19k9aK9KYuLyXSgi/X1o+qqotI08nm6yY/oBsSw4h2kWDeOOw0o7PmYdx6YAizcMZnCnhq7M7aTDYa5RbGNm8BoYx7TNKorSnKxUVlf68ETmu+7R6Jv5dGdOVCpsWsx0z9Ii/98fPtzPjvLyvFznnDjCvJshc1BikPWs4Apfda7EJkZgXdIlNauW1p1JC1LJ5RIJ1lWVl/ebUcTTJdVlXboXbEvaAPIf7dR2nyAxOF5fYhq9hvxBKgNetCZEknltAcrpFwcjKSMN0ZBNyFoVhiH2VFqxANfBsU/RbkZaaluauuwaB7Nn9d96lHuuktw3a9n+WXNuB96/VkBqXnwJvfyrONOIShIsjs4U+uGU9GiYYqy9VxIO9HQMC2LSOzs/SH8CzO51ToLxB5GlEiVKBQwhAIH/sCG+ube0RUAPTYMZFtV/ITAXFXFuiJ4LtFO4jht1IxCzWgL1KrRhblOhhixj5jQ=
language: java
jdk:
- openjdk8
- oraclejdk8
install: true
before_install:
- sudo apt update -y || true
- sudo apt install -y --no-install-recommends docker-ce python-pip curl jq libxml2-utils
- sudo pip install docker-compose httpie
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080 9990 9999 5005
script:
- bash gradlew clean docs -Dorg.ajoberstar.grgit.auth.username=$GITHUB_USERNAME -Dorg.ajoberstar.grgit.auth.password=$GITHUB_PASSWORD
#
- export root=$(pwd)
#
- cd ${root}/java-ee
- bash mvnw
- docker-compose -f docker-compose-maven.yaml build
- docker-compose -f docker-compose-maven.yaml up &
- sleep 40
- http post :8080/app/facebook/create postId=post1
- http put http://localhost:8080/app/facebook/post1/like
- http put http://localhost:8080/app/facebook/post1/dislike
- http put http://localhost:8080/app/facebook/post1/like
- http put http://localhost:8080/app/facebook/post1/like
- http :8080/app/posts/post1
- http :8080/app/posts/post1/events
- docker-compose -f docker-compose-maven.yaml down -v
#
- bash gradlew
- bash gradlew composeUp
- sleep 20
- http post :8080/app/facebook/create postId=post2
- http put http://localhost:8080/app/facebook/post2/dislike
- http :8080/app/posts
- http :8080/app/posts/post2/events
- bash gradlew composeDown
