version: "2.1"

services:

  gradle-axom-micro-app:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes: ["gradle-axom-micro-app-data:/home/appuser"]
    networks: [backing-services]
    ports: ["8080:8080"]
    #restart: unless-stopped
    #mem_limit: 838860800 # 800Mb

volumes:
  gradle-axom-micro-app-data: {}

networks:
  backing-services:
    driver: bridge
